/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, line_points[0],line_points[1], (0, 255, 255), 2)
SystemError: new style getargs format but argument is not a tuple
/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, line_points[0],line_points[1], (0, 255, 255), 2)
SystemError: new style getargs format but argument is not a tuple
/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, tuple(line_points[0]),tuple(line_points[1]), (0, 255, 255), 2)
TypeError: integer argument expected, got float
/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, tuple(int(line_points[0])),tuple(int(line_points[1])), (0, 255, 255), 2)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, tuple(int(line_points[0][0]),int(line_points[0][1])),tuple(int(line_points[1][0]),int(line_points[1][1])), (0, 255, 255), 2)
TypeError: tuple expected at most 1 arguments, got 2
/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 21, in <module>
    cv2.line(image, tuple({int(line_points[0][0]),int(line_points[0][1])}),tuple({int(line_points[1][0]),int(line_points[1][1])}), (0, 255, 255), 2)
TypeError: function takes exactly 2 arguments (1 given)
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0xf0a3c0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "/home/pi/tf_inference/liveView.py", line 7, in <module>
    camera = PiCamera()
  File "/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/home/pi/tf_inference/tflite1-env/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
